- name: Clone Kubespray
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    dest: ~/kubespray
    version: master

- name: Install Python dependencies
  pip:
    requirements: ~/kubespray/requirements.txt
    executable: pip3

- name: Generate Kubespray inventory
  command: >
    python3 ~/kubespray/contrib/inventory_builder/inventory.py
    {{ groups['kube_nodes'] | join(' ') }}
  args:
    chdir: ~/kubespray

- name: Deploy HA Kubernetes cluster
  command: >
    ansible-playbook -i ~/kubespray/inventory/mycluster/hosts.yaml
    --become --become-user=root
    ~/kubespray/cluster.yml
