
#################
# 0️⃣ Remove old Kubespray if exists
- name: Remove old Kubespray directory
  file:
    path: /home/pisethkhon888/k8s/kubespray
    state: absent

#1️⃣ Clone Kubespray
- name: Clone Kubespray
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    dest: /home/pisethkhon888/k8s/kubespray
    version: master
  ignore_errors: yes

# 4️⃣ Install required Python packages
- name: Install Python requirements for Kubespray
  pip:
    requirements: "{{ kubespray_dir }}/requirements.txt"
    executable: /usr/bin/pip3
  
- name: Remove Git and CI directories from Kubespray
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /home/pisethkhon888/k8s/kubespray/.git
    - /home/pisethkhon888/k8s/kubespray/.github
    - /home/pisethkhon888/k8s/kubespray/.gitlab-ci

#################
# - name: Load GCP instances from JSON
#   set_fact:
#     gcp_data: "{{ lookup('file', '/home/pisethkhon888/k8s/gcp_instance.json') | from_json }}"

# # option1
# - name: Copy inventory.ini.j2 to inventory.ini
#   copy:
#     src: /home/pisethkhon888/k8s/inventory/mycluster/inventory.ini.j2
#     dest: /home/pisethkhon888/k8s/inventory/mycluster/inventory.ini
#     mode: '0644'

#################
# option 2
- name: Overwrite Kubespray inventory.ini with custom configuration
  template:
    src: "inventory.ini.j2"
    dest: "/home/pisethkhon888/k8s/kubespray/inventory/sample/inventory.ini"
    mode: '0644'
  vars:
    workers: "{{ gcp_data.workers }}"


- name: Enable Kubernetes dashboard
  replace:
    path: "/home/pisethkhon888/k8s/kubespray/inventory/sample/group_vars/k8s_cluster/addons.yml"
    regexp: "^#\\s*dashboard_enabled:.*"
    replace: "dashboard_enabled: true"

- name: Enable Kubernetes addons
  replace:
    path: "/home/pisethkhon888/k8s/kubespray/inventory/sample/group_vars/k8s_cluster/addons.yml"
    regexp: "^{{ item }}:\\s*false"
    replace: "{{ item }}: true"
  loop:
    - helm_enabled
    - argocd_enabled
    - metrics_server_enabled
    - cert_manager_enabled
    - ingress_nginx_enabled

# 
- name:  Kubernetes change  cluster_name 
  replace:
    path: "/home/pisethkhon888/k8s/kubespray/inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml"
    regexp: "^{{ item }}:\\s*cluster.local"
    replace: "{{ item }}: pro.cluster"
  loop:
    - cluster_name
#################


# 1️⃣ Load GCP instance data
- name: Load worker nodes from JSON
  include_vars:
    file: /home/pisethkhon888/k8s/gcp_instance.json
    name: gcp_data

# 2️⃣ Set master and workers facts
- name: Set master and worker facts
  set_fact:
    master:
      name: master1
      internal_ip: 10.148.0.14
      external_ip: 34.124.178.96
    workers: "{{ gcp_data.workers }}"

# 3️⃣ Debug to confirm
- name: Debug master
  debug:
    var: master

- name: Debug workers
  debug:
    var: workers
# # Ensure inventory directory exists
# - name: Ensure inventory directory exists
#   file:
#     path: "{{ kubespray_dir }}/inventory/mycluster"
#     state: directory
#     mode: '0755'

# # Generate dynamic hosts.yml
# - name: Generate dynamic hosts.yml
#   template:
#     src: /home/pisethkhon888/k8s/inventory/mycluster/inventory.ini.j2
#     dest: "/home/pisethkhon888/k8s/inventory/mycluster/inventory.ini"
# # 

# 2️⃣ Set master and workers facts
# - name: Set master and worker facts
#   set_fact:
#     master:
#       name: master1
#       internal_ip: 10.148.0.14
#       external_ip: 34.124.178.96
#     workers: "{{ gcp_data.workers }}"

# # 3️⃣ Debug to confirm
# - name: Debug master
#   debug:
#     var: master

- name: Set worker IPs list
  set_fact:
    worker_ips: "{{ gcp_data.workers | map(attribute='internal_ip') | list }}"

# - name: Debug worker IPs
#   debug:
#     var: worker_ips
# 1️⃣ Wait for master SSH
- name: Wait for master SSH
  wait_for:
    host: "10.148.0.14"
    port: 22
    state: started
    timeout: 300


- name: Wait for worker SSH
  wait_for:
    host: "{{ item }}"
    port: 22
    state: started
    timeout: 300
  loop: "{{ worker_ips }}"

#################
# 4️⃣ Copy SSH key to master
# - name: Copy SSH key to master
#   authorized_key:
#     user: pisethkhon888
#     state: present
#     key: "{{ lookup('file', ssh_public_key_file) }}"
#   delegate_to: "10.148.0.14 "
#   vars:
#     ansible_ssh_private_key_file: "{{ ssh_private_key_file }}"


   # # 5️⃣ Copy SSH key to worker nodes
- name: Copy SSH key to worker nodes
  authorized_key:
    user: pisethkhon888
    state: present
    key: "{{ lookup('file', ssh_public_key_file) }}"
  loop: "{{ worker_ips }}"
  delegate_to: "{{ item }}"
  vars:
    ansible_ssh_private_key_file: "{{ ssh_private_key_file }}"
#################
# option1 static
# - name: Ensure inventory directory exists
#   file:
#     path: /home/pisethkhon888/kubespray/inventory/mycluster
#     state: directory
#     mode: '0755' # is a safe default for directories that Ansible needs to write files into.



# 2️⃣ Update inventory hosts (masters/workers) dynamically
# - name: Update inventory hosts
#   template:
#     src: hosts.yaml.j2
#     dest: "{{ kubespray_dir }}/inventory/mycluster/hosts.yaml"

# # 3️⃣ Update cluster variables (all.yml)
# - name: Set cluster variables
#   template:
#     src: all.yml.j2
#     dest: "{{ kubespray_dir }}/inventory/mycluster/group_vars/all.yml"
# 5️⃣ add  cluster addons
# - name: Enable cluster addons
#   blockinfile:
#     path: "/home/pisethkhon888/kubespray/inventory/sample/group_vars/k8s_cluster/addons.yml"
#     create: yes
#     block: |
#       dashboard_enabled: true
#       helm_enabled: true
#       argocd_enabled: true
#       metrics_server_enabled: true
#       cert_manager_enabled: true
#       ingress_nginx_enabled: true




# ############
# 2️⃣ reset Kubespray to setup HA cluster
# - name: reset kubernetes
#   command: >
#     ansible-playbook -b -v
#     -i /home/pisethkhon888/k8s/kubespray/inventory/sample/inventory.ini
#     reset.yml
#   args:
#     chdir: "/home/pisethkhon888/k8s/kubespray"

# 2️⃣ Run Kubespray to setup HA cluster
- name: Run Kubespray to setup HA cluster
  command: >
    ansible-playbook -b -v
    -i /home/pisethkhon888/k8s/kubespray/inventory/sample/inventory.ini
    cluster.yml
  args:
    chdir: "/home/pisethkhon888/k8s/kubespray"
# ############


