- name: Wait for master1 SSH to be ready
  wait_for:
    # host: "{{ hostvars['master1'].ansible_host }}"
    host: "10.148.0.14"
    port: 22
    state: started
    timeout: 300

- name: Check if SSH public key exists
  stat:
    path: "{{ ssh_public_key_file }}"
  register: ssh_pubkey_stat

- name: Generate SSH key pair if no public key exists
  shell: ssh-keygen -t rsa -b 4096 -f {{ ssh_private_key_file }} -N ''
  when: ssh_pubkey_stat.stat.exists == false

- name: Slurp SSH public key
  slurp:
    src: "{{ ssh_public_key_file }}"
  register: ssh_pubkey

- name: Create worker nodes
  google.cloud.gcp_compute_instance:
    name: "{{ item.name }}"
    machine_type: "{{ item.machine_type }}"
    zone: "{{ item.zone }}"
    project: "{{ google_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ cloud_credentials_file }}"
    state: present
    metadata:
      ssh-keys: "{{ ansible_user }}:{{ ssh_pubkey['content'] | b64decode }}"
    disks:
      - auto_delete: true
        boot: true
        initialize_params:
          source_image: "{{ item.image }}"
          disk_size_gb: "{{ item.disk_size }}"
          disk_type: "{{ item.disk_type }}"
    network_interfaces:
      - network:
          selfLink: "projects/{{ google_project_id }}/global/networks/default"
        access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
    tags:
      items:
        - http-server
        - https-server
  loop: "{{ machines_info }}"
  register: created_workers


# 5️⃣ Wait for worker nodes SSH
- name: Wait for worker nodes SSH
  wait_for:
    host: "{{ item.networkInterfaces[0].accessConfigs[0].natIP }}"
    port: 22
    state: started
    timeout: 300
  loop: "{{ created_workers.results }}"

- name: Save worker node IPs to gcp_instance.json
  template:
    src: gcp_instance.json.j2
    dest: /home/pisethkhon888/k8s/gcp_instance.json
  when: created_workers is defined

# - name: Save worker node IPs to gcp_instance.json
#   copy:
#     dest: /home/pisethkhon888/k8s/gcp_instance.json
#     content: |
#       { "workers": [
#         {% for item in created_workers.results %}
#         {
#           "name": "{{ item.item.name }}",
#           "internal_ip": "{{ item.data.networkInterfaces[0].networkIP }}",
#           "external_ip": "{{ item.data.networkInterfaces[0].accessConfigs[0].natIP }}"
#         }{% if not loop.last %},{% endif %}
#         {% endfor %}
#       ] }
#   when: created_workers is defined




# - name: Save worker node IPs from machines_info
#   copy:
#     dest: /home/pisethkhon888/k8s/gcp_instance.json
#     content: |
#       {{
#         machines_info | map(attribute='name') | zip(
#         machines_info | map(attribute='ansible_host') ) | map('list') | list | to_json
#       }}
#   when: machines_info is defined


