
# roles/ingress/tasks/main.yml

# vars can be defined in your playbook or inventory
# gcp_project: your GCP project ID
# gcp_zone: zone of your master.external_ip node (e.g., asia-east2-b)
# kubespray_dir: path to your kubespray directory
# 0️⃣ Requirements
# - name: Ensure Python dependencies for Kubernetes modules
#   pip:
#     name:
#       - kubernetes
#       - google-auth
#       - requests
#     executable: /usr/bin/pip3
#   become: yes
# 8️⃣ Install Nginx Ingress Controller
# - name: Install Nginx Ingress Controller
#   kubernetes.core.k8s:
#     state: present
#     # kubeconfig: "{{ kubespray_dir }}/inventory/mycluster/artifacts/admin.conf"
#     definition: "{{ lookup('file', '{{ kubespray_dir }}/roles/ingress/templates/ingress.yaml') }}"


# roles/ingress/tasks/main.yml

  # 7️⃣ Install Nginx Ingress Controller (Optional)
  - name: Install Nginx Ingress Controller
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('file', '/home/pisethkhon888/k8s/roles/ingress/templates/ingress.yaml') }}"
    delegate_to: localhost

# - name: Install Nginx Ingress Controller
#   kubernetes.core.k8s:
#     state: present
#     definition: "{{ lookup('file', '/home/pisethkhon888/k8s/roles/ingress/templates/ingress.yaml') }}"

