all:
  hosts:
    master1:
      ansible_host: 34.124.178.96
      ansible_user: pisethkhon888
      ansible_ssh_private_key_file: /home/pisethkhon888/.ssh/id_rsa
      children:
    kube_control_plane:
      hosts:
        master1:
    kube_nodes:
      hosts:
            etcd:
      hosts:
        master1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_nodes:
